# - Find SWSCALE
# Find the native SWSCALE includes and library
# This module defines
#  SWSCALE_INCLUDE_DIR, where to find jpeglib.h, etc.
#  SWSCALE_LIBRARIES, the libraries needed to use SWSCALE.
#  SWSCALE_FOUND, If false, do not try to use SWSCALE.
# also defined, but not for general use are
#  SWSCALE_LIBRARY, where to find the SWSCALE library.

FIND_PATH(SWSCALE_INCLUDE_DIR swscale.h PATHS /usr/local/include /usr/include PATH_SUFFIXES ffmpeg libswscale )

SET(SWSCALE_NAMES ${SWSCALE_NAMES} swscale)
FIND_LIBRARY(SWSCALE_LIBRARY
  NAMES ${SWSCALE_NAMES}
  PATHS /usr/lib /usr/local/lib
  )

IF (SWSCALE_LIBRARY AND SWSCALE_INCLUDE_DIR)
    SET(SWSCALE_LIBRARIES ${SWSCALE_LIBRARY})
    SET(SWSCALE_FOUND "YES")
ELSE (SWSCALE_LIBRARY AND SWSCALE_INCLUDE_DIR)
  SET(SWSCALE_FOUND "NO")
ENDIF (SWSCALE_LIBRARY AND SWSCALE_INCLUDE_DIR)


IF (SWSCALE_FOUND)
   IF (NOT SWSCALE_FIND_QUIETLY)
      MESSAGE(STATUS "Found SWSCALE: ${SWSCALE_LIBRARIES}")
   ENDIF (NOT SWSCALE_FIND_QUIETLY)
ELSE (SWSCALE_FOUND)
   IF (SWSCALE_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find SWSCALE library")
   ENDIF (SWSCALE_FIND_REQUIRED)
ENDIF (SWSCALE_FOUND)

# Deprecated declarations.
SET (NATIVE_SWSCALE_INCLUDE_PATH ${SWSCALE_INCLUDE_DIR} )
GET_FILENAME_COMPONENT (NATIVE_SWSCALE_LIB_PATH ${SWSCALE_LIBRARY} PATH)

MARK_AS_ADVANCED(
  SWSCALE_LIBRARY
  SWSCALE_INCLUDE_DIR
  )

