# - Find AVUTIL
# Find the native AVUTIL includes and library
# This module defines
#  AVUTIL_INCLUDE_DIR, where to find jpeglib.h, etc.
#  AVUTIL_LIBRARIES, the libraries needed to use AVUTIL.
#  AVUTIL_FOUND, If false, do not try to use AVUTIL.
# also defined, but not for general use are
#  AVUTIL_LIBRARY, where to find the AVUTIL library.

FIND_PATH(AVUTIL_INCLUDE_DIR avutil.h PATHS /usr/local/include /usr/include PATH_SUFFIXES ffmpeg libavutil)

SET(AVUTIL_NAMES ${AVUTIL_NAMES} avutil)
FIND_LIBRARY(AVUTIL_LIBRARY
  NAMES ${AVUTIL_NAMES}
  PATHS /usr/lib /usr/local/lib
  )

IF (AVUTIL_LIBRARY AND AVUTIL_INCLUDE_DIR)
    SET(AVUTIL_LIBRARIES ${AVUTIL_LIBRARY})
    SET(AVUTIL_FOUND "YES")
ELSE (AVUTIL_LIBRARY AND AVUTIL_INCLUDE_DIR)
  SET(AVUTIL_FOUND "NO")
ENDIF (AVUTIL_LIBRARY AND AVUTIL_INCLUDE_DIR)


IF (AVUTIL_FOUND)
   IF (NOT AVUTIL_FIND_QUIETLY)
      MESSAGE(STATUS "Found AVUTIL: ${AVUTIL_LIBRARIES}")
   ENDIF (NOT AVUTIL_FIND_QUIETLY)
ELSE (AVUTIL_FOUND)
   IF (AVUTIL_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find AVUTIL library")
   ENDIF (AVUTIL_FIND_REQUIRED)
ENDIF (AVUTIL_FOUND)

# Deprecated declarations.
SET (NATIVE_AVUTIL_INCLUDE_PATH ${AVUTIL_INCLUDE_DIR} )
GET_FILENAME_COMPONENT (NATIVE_AVUTIL_LIB_PATH ${AVUTIL_LIBRARY} PATH)

MARK_AS_ADVANCED(
  AVUTIL_LIBRARY
  AVUTIL_INCLUDE_DIR
  )

