# - Find AVFORMAT
# Find the native AVFORMAT includes and library
# This module defines
#  AVFORMAT_INCLUDE_DIR, where to find jpeglib.h, etc.
#  AVFORMAT_LIBRARIES, the libraries needed to use AVFORMAT.
#  AVFORMAT_FOUND, If false, do not try to use AVFORMAT.
# also defined, but not for general use are
#  AVFORMAT_LIBRARY, where to find the AVFORMAT library.

FIND_PATH(AVFORMAT_INCLUDE_DIR avformat.h PATHS /usr/local/include /usr/include PATH_SUFFIXES ffmpeg libavformat)

SET(AVFORMAT_NAMES ${AVFORMAT_NAMES} avformat)
FIND_LIBRARY(AVFORMAT_LIBRARY
  NAMES ${AVFORMAT_NAMES}
  PATHS /usr/lib /usr/local/lib
  )

IF (AVFORMAT_LIBRARY AND AVFORMAT_INCLUDE_DIR)
    SET(AVFORMAT_LIBRARIES ${AVFORMAT_LIBRARY})
    SET(AVFORMAT_FOUND "YES")
ELSE (AVFORMAT_LIBRARY AND AVFORMAT_INCLUDE_DIR)
  SET(AVFORMAT_FOUND "NO")
ENDIF (AVFORMAT_LIBRARY AND AVFORMAT_INCLUDE_DIR)


IF (AVFORMAT_FOUND)
   IF (NOT AVFORMAT_FIND_QUIETLY)
      MESSAGE(STATUS "Found AVFORMAT: ${AVFORMAT_LIBRARIES}")
   ENDIF (NOT AVFORMAT_FIND_QUIETLY)
ELSE (AVFORMAT_FOUND)
   IF (AVFORMAT_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find AVFORMAT library")
   ENDIF (AVFORMAT_FIND_REQUIRED)
ENDIF (AVFORMAT_FOUND)

# Deprecated declarations.
SET (NATIVE_AVFORMAT_INCLUDE_PATH ${AVFORMAT_INCLUDE_DIR} )
GET_FILENAME_COMPONENT (NATIVE_AVFORMAT_LIB_PATH ${AVFORMAT_LIBRARY} PATH)

MARK_AS_ADVANCED(
  AVFORMAT_LIBRARY
  AVFORMAT_INCLUDE_DIR
  )

