# - Find PTHREAD
# Find the native PTHREAD includes and library
# This module defines
#  PTHREAD_INCLUDE_DIR, where to find jpeglib.h, etc.
#  PTHREAD_LIBRARIES, the libraries needed to use PTHREAD.
#  PTHREAD_FOUND, If false, do not try to use PTHREAD.
# also defined, but not for general use are
#  PTHREAD_LIBRARY, where to find the PTHREAD library.

FIND_PATH(PTHREAD_INCLUDE_DIR pthread.h
/usr/local/include
/usr/include
)

SET(PTHREAD_NAMES ${PTHREAD_NAMES} pthread)
FIND_LIBRARY(PTHREAD_LIBRARY
  NAMES ${PTHREAD_NAMES}
  PATHS /usr/lib /usr/local/lib
  )

IF (PTHREAD_LIBRARY AND PTHREAD_INCLUDE_DIR)
    SET(PTHREAD_LIBRARIES ${PTHREAD_LIBRARY})
    SET(PTHREAD_FOUND "YES")
ELSE (PTHREAD_LIBRARY AND PTHREAD_INCLUDE_DIR)
  SET(PTHREAD_FOUND "NO")
ENDIF (PTHREAD_LIBRARY AND PTHREAD_INCLUDE_DIR)


IF (PTHREAD_FOUND)
   IF (NOT PTHREAD_FIND_QUIETLY)
      MESSAGE(STATUS "Found PTHREAD: ${PTHREAD_LIBRARIES}")
   ENDIF (NOT PTHREAD_FIND_QUIETLY)
ELSE (PTHREAD_FOUND)
   IF (PTHREAD_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find PTHREAD library")
   ENDIF (PTHREAD_FIND_REQUIRED)
ENDIF (PTHREAD_FOUND)

# Deprecated declarations.
SET (NATIVE_PTHREAD_INCLUDE_PATH ${PTHREAD_INCLUDE_DIR} )
GET_FILENAME_COMPONENT (NATIVE_PTHREAD_LIB_PATH ${PTHREAD_LIBRARY} PATH)

MARK_AS_ADVANCED(
  PTHREAD_LIBRARY
  PTHREAD_INCLUDE_DIR
  )

