/*
 * This file is part of Lighttwist.
 * 
 * @Copyright 2004-2008 Université de Montréal, Laboratoire Vision3D
 *   Sébastien Roy (roys@iro.umontreal.ca)
 *   Vincent Chapdelaine-Couture (chapdelv@iro.umontreal.ca)
 *   Louis Bouchard (lwi.bouchard@gmail.com)
 *   Jean-Philippe Tardif
 *   Patrick Holloway
 *   Nicolas Martin
 *   Vlad Lazar
 *   Jamil Draréni 
 *   Marc-Antoine Drouin
 * @Copyright 2005-2007 Société des arts technologiques
 *
 * Lighttwist is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Lighttwist is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Lighttwist.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef WINDOW_INTERFACE_H
#define WINDOW_INTERFACE_H

#include <string.h>
#include "FL/Fl_Input.H"
#include "FL/Fl_Spinner.H"
#include "FL/Fl_Choice.H"
#include "FL/Fl_Check_Button.H"
#include "FL/Fl_Slider.H"
#include "FL/Fl_Text_Display.H"
#include "FL/Fl_Box.H"
#include "FL/fl_draw.H"
#include "DnDBox.h"
#include <utils/entry.h>

//this is needed to define our own box drawing function
#define BOX_USER_DRAW FL_FREE_BOXTYPE

#define BUFLEN 255

#define FONTFACE FL_HELVETICA
#define FONTSIZE 12
#define OFFSET 10
#define WIDGET_WIDTH 110
#define LINESPACE 28

#define BCKGRND_INTENSITY 0.8
#define MENU_INTENSITY 0.78
#define BORDER_INTENSITY 0.5

#define SMALL_WIDGET_WIDTH WIDGET_WIDTH*3/4

#define VERY_SMALL_WIDGET w()-WIDGET_WIDTH/2-3*OFFSET,LINEPOSY,WIDGET_WIDTH/2,FONTSIZE+OFFSET
#define SMALL_WIDGET w()-WIDGET_WIDTH*3/4-3*OFFSET,LINEPOSY,WIDGET_WIDTH*3/4,FONTSIZE+OFFSET
#define STANDARD_WIDGET w()-WIDGET_WIDTH-3*OFFSET,LINEPOSY,WIDGET_WIDTH,FONTSIZE+OFFSET
#define BIG_WIDGET w()-3*WIDGET_WIDTH/2-3*OFFSET,LINEPOSY,3*WIDGET_WIDTH/2,FONTSIZE+OFFSET
#define LARGE_WIDGET w()-2*WIDGET_WIDTH-3*OFFSET,LINEPOSY,2*WIDGET_WIDTH,FONTSIZE+OFFSET
#define VERY_LARGE_WIDGET w()-3*WIDGET_WIDTH-3*OFFSET,LINEPOSY,3*WIDGET_WIDTH,FONTSIZE+OFFSET

#define STATUS_BAR_HEIGHT 25

#define PLANAR_CONFIGURATION 0
#define HOMOGRAPHY_CONFIGURATION 1
#define CYCLORAMA_CONFIGURATION 2
#define BEZIER_CONFIGURATION 3

#define THREADING_SINGLE 0
#define THREADING_MULTI 1

#define PLAYER_DEFAULT 0
#define PLAYER_LUA 1

#define STATS_FILE "FILE"
#define STATS_LENGTH "LENGTH"
#define STATS_FPS "FPS"
#define STATS_TYPE "TYPE"
#define STATS_WIDTH "WIDTH"
#define STATS_HEIGHT "HEIGHT"

#define CMD_STL "ltstl"
#define CMD_SELECT "ltselect"
#define CMD_SUM "ltsum"
#define CMD_CAM2PROJ "ltcam2proj"
#define CMD_CAM2PROJ_NOISE "ltcam2proj-noise"
#define CMD_SMOOTH "ltsmooth-homography"
#define CMD_BLEND "ltblend-diffuse"
//define CMD_BLEND "ltmaxblend"
#define CMD_UV2PROJ "ltuv2proj"
#define CMD_GAMMA "ltgamma"
#define CMD_COLOR "ltcolor"
#define CMD_COLOR_FIT "ltcolorfit"
#define CMD_PLAYER_DEFAULT "ltplayer"
#define CMD_PLAYER_LUA "ltplayerlua"
#define CMD_PRECROP "ltprecrop"
#define CMD_JOYSTICK_CONTROL "ltjoystick"

#define MEDIA_X 10
#define MEDIA_Y 10

#define CAMERA_GPHOTO2 "gPhoto2"
#define CAMERA_V4L "Video4Linux"
#define CAMERA_PROSILICA "Prosilica"

#define TEST_PATTERN_WHITE 0
#define TEST_PATTERN_BLACK 1
#define TEST_PATTERN_CHECKER 2
#define TEST_PATTERN_MAX 3

//#define STL_PATTERNS_NB 40
#define STL_GAMMA_NB 36
#define STL_COLOR_NB 24

#define USER_ADMIN 0
#define USER_ARTIST 1
#define USER_ADMIN_STR "admin"
#define USER_ARTIST_STR_FR "artiste"
#define USER_ARTIST_STR_EN "artist"

#define CHANNEL_MONO 0
#define CHANNEL_LEFT 0
#define CHANNEL_RIGHT 1

#define LAYER_TYPE_VIDEO 0
#define LAYER_TYPE_AUDIO 1
#define LAYER_TYPE_3D 2

#define SHELL_HIDDEN 0
#define SHELL_VISIBLE 1

#define SHELL_NON_BLOCKING 0
#define SHELL_BLOCK 1

#define BUTTON_ON 0
#define BUTTON_OFF 1
#define BUTTON_DISABLED 2

#define NB_LANG 2
#define LANG_ENGLISH 0
#define LANG_FRENCH 1
#define LANG_ENGLISH_STR "en"
#define LANG_FRENCH_STR "fr"

#define LABEL_WELCOME 0
#define LABEL_YES 1
#define LABEL_NO 2
#define LABEL_OK 3
#define LABEL_CANCEL 4
#define LABEL_RESET 5
#define LABEL_REFRESH 6
#define LABEL_CLOSE 7
#define LABEL_UNDO 8
#define LABEL_APPLY 9

#define LABEL_MENU 20
#define LABEL_MENU_PROJECT 20+0
#define LABEL_MENU_PROJECT_OPEN 20+1
#define LABEL_MENU_PROJECT_EDIT 20+2
#define LABEL_MENU_PROJECT_SAVE 20+3
#define LABEL_MENU_PROJECT_QUIT 20+4
#define LABEL_MENU_HELP_ONLINE 20+5
#define LABEL_MENU_HELP_PROBLEM 20+6
#define LABEL_MENU_HELP_ABOUT 20+7
#define LABEL_MENU_HELP 20+8
#define LABEL_MACHINE_IP 20+9
#define LABEL_MACHINE_IP_SPACE 20+10
#define LABEL_MACHINES 20+11
#define LABEL_BROWSE 20+12

#define LABEL_PROJECT 40
#define LABEL_PROJECT_NAME LABEL_PROJECT+0
#define LABEL_PROJECT_MODE LABEL_PROJECT+1
#define LABEL_CONFIGURATION_HOMOGRAPHY LABEL_PROJECT+2
#define LABEL_PROJECT_VMIRROR LABEL_PROJECT+3
#define LABEL_PROJECT_RATIO LABEL_PROJECT+4
#define LABEL_PROJECT_NB_PROJECTORS LABEL_PROJECT+5
#define LABEL_PROJECT_CONFIGURATION LABEL_PROJECT+6
#define LABEL_PROJECT_RESOLUTION LABEL_PROJECT+7
#define LABEL_PROJECT_NB_SPEAKERS LABEL_PROJECT+8
#define LABEL_PROJECT_MEDIA_DIRECTORY LABEL_PROJECT+9
#define LABEL_PROJECT_LOCAL_SCAN_DIRECTORY LABEL_PROJECT+10
#define LABEL_PROJECT_LOCAL_DATA_DIRECTORY LABEL_PROJECT+11
#define LABEL_PROJECT_LOCAL_BIN_DIRECTORY LABEL_PROJECT+12
#define LABEL_PROJECT_LOCAL_LIB_DIRECTORY LABEL_PROJECT+13
#define LABEL_PROJECT_LOCAL_SHARE_DIRECTORY LABEL_PROJECT+14
#define LABEL_PROJECT_REMOTE_SCAN_DIRECTORY LABEL_PROJECT+15
#define LABEL_PROJECT_REMOTE_DATA_DIRECTORY LABEL_PROJECT+16
#define LABEL_PROJECT_REMOTE_BIN_DIRECTORY LABEL_PROJECT+17
#define LABEL_PROJECT_REMOTE_SHARE_DIRECTORY LABEL_PROJECT+18
#define LABEL_PROJECT_SOUND_CTRL_IP LABEL_PROJECT+19
#define LABEL_PROJECT_ENABLE_JACK LABEL_PROJECT+20
#define LABEL_MODE_MONO LABEL_PROJECT+21
#define LABEL_MODE_STEREO_RC LABEL_PROJECT+22
#define LABEL_MODE_STEREO_P LABEL_PROJECT+23
#define LABEL_MODE_STEREO_SYNC LABEL_PROJECT+24

#define LABEL_WINDOWS 70
#define LABEL_BLEND_WINDOW_TITLE LABEL_WINDOWS+0
#define LABEL_CAM2PROJ_WINDOW_TITLE LABEL_WINDOWS+1
#define LABEL_UV2PROJ_WINDOW_TITLE LABEL_WINDOWS+2
#define LABEL_COLOR_WINDOW_TITLE LABEL_WINDOWS+3
#define LABEL_UVMAP_WINDOW_TITLE LABEL_WINDOWS+4
#define LABEL_GAMMA_WINDOW_TITLE LABEL_WINDOWS+5
#define LABEL_PATTERN_WINDOW_TITLE LABEL_WINDOWS+6
#define LABEL_CAPTURE_WINDOW_TITLE LABEL_WINDOWS+7
#define LABEL_MEDIA_WINDOW_TITLE LABEL_WINDOWS+8
#define LABEL_PLAY_WINDOW_TITLE LABEL_WINDOWS+9
#define LABEL_PRECROP_WINDOW_TITLE LABEL_WINDOWS+10
#define LABEL_PROJECT_WINDOW_TITLE LABEL_WINDOWS+11
#define LABEL_SHELL_WINDOW_TITLE LABEL_WINDOWS+12
#define LABEL_SMOOTH_WINDOW_TITLE LABEL_WINDOWS+13
#define LABEL_LIVE_WINDOW_TITLE LABEL_WINDOWS+14

#define LABEL_TABS 90
#define LABEL_TAB_SETUP LABEL_TABS+0
#define LABEL_TAB_SCAN LABEL_TABS+1
#define LABEL_TAB_SOUND LABEL_TABS+2
#define LABEL_TAB_MEDIA LABEL_TABS+3
#define LABEL_TAB_PLAYLIST LABEL_TABS+4
#define LABEL_TAB_SHOW LABEL_TABS+5
#define LABEL_TEST_PATTERN LABEL_TABS+6
#define LABEL_TEST_WHITE LABEL_TABS+7
#define LABEL_TEST_BLACK LABEL_TABS+8
#define LABEL_TEST_CHECKER LABEL_TABS+9
#define LABEL_RECONNECT_ALL LABEL_TABS+10
#define LABEL_TEST LABEL_TABS+11
#define LABEL_TEST_ALL LABEL_TABS+12
#define LABEL_SCAN_PATTERN LABEL_TABS+13
#define LABEL_SCAN_CAPTURE LABEL_TABS+14
#define LABEL_SCAN_SELECT LABEL_TABS+15
#define LABEL_SCAN_SUM LABEL_TABS+16
#define LABEL_SCAN_UVMAP LABEL_TABS+17
#define LABEL_SCAN_CAM2PROJ LABEL_TABS+18
#define LABEL_SCAN_SMOOTH LABEL_TABS+19
#define LABEL_SCAN_GAMMA LABEL_TABS+20
#define LABEL_SCAN_COLOR LABEL_TABS+21
#define LABEL_SCAN_BLEND LABEL_TABS+22
#define LABEL_SCAN_UV2PROJ LABEL_TABS+23
#define LABEL_SCAN_CALIBRATE LABEL_TABS+24
#define LABEL_SCAN_MODE LABEL_TABS+25
#define LABEL_SCAN_NORMAL LABEL_TABS+26
#define LABEL_SCAN_ADVANCED LABEL_TABS+27
#define LABEL_MEDIA_TREE LABEL_TABS+28
#define LABEL_IMPORT_MEDIA LABEL_TABS+29
#define LABEL_AUTO_PLAYLIST LABEL_TABS+30
#define LABEL_SELECTED_MEDIA LABEL_TABS+31
#define LABEL_REMOVE_MEDIA LABEL_TABS+32
#define LABEL_CURRENT_MEDIA LABEL_TABS+33
#define LABEL_SAVE_PLAYLIST LABEL_TABS+34
#define LABEL_LOAD_PLAYLIST LABEL_TABS+35
#define LABEL_STATUS LABEL_TABS+36
#define LABEL_TIMESCALE LABEL_TABS+37
#define LABEL_VIDEO_LAYER LABEL_TABS+38
#define LABEL_AUDIO_LAYER LABEL_TABS+39
#define LABEL_EXT_VIDEO LABEL_TABS+40
#define LABEL_EXT_AUDIO LABEL_TABS+41
#define LABEL_EXT_3D LABEL_TABS+42
#define LABEL_EXT_IMAGE LABEL_TABS+43
#define LABEL_EXT_STATS LABEL_TABS+44
#define LABEL_EXT_PLAYLIST LABEL_TABS+45
#define LABEL_REMOVE LABEL_TABS+46
#define LABEL_NO_DATA LABEL_TABS+47
#define LABEL_MASTER_VIDEO LABEL_TABS+48
#define LABEL_MASTER_AUDIO LABEL_TABS+49
#define LABEL_PLAYER_THREADING LABEL_TABS+50
#define LABEL_PLAYER_SELECT LABEL_TABS+51
#define LABEL_PLAYER_SINGLE_THREAD LABEL_TABS+52
#define LABEL_PLAYER_MULTI_THREAD LABEL_TABS+53
#define LABEL_PLAYER_DEFAULT LABEL_TABS+54
#define LABEL_PLAYER_LUA LABEL_TABS+55
#define LABEL_SCENE_SCALE LABEL_TABS+56
#define LABEL_STEREO_B LABEL_TABS+57
#define LABEL_STEREO_R LABEL_TABS+58
#define LABEL_SOUND_SCALE LABEL_TABS+59
#define LABEL_STEREO_DISTORT LABEL_TABS+60
#define LABEL_STEREO_SLIT LABEL_TABS+61
#define LABEL_RED LABEL_TABS+62
#define LABEL_GREEN LABEL_TABS+63
#define LABEL_BLUE LABEL_TABS+64
#define LABEL_ADD_SOUNDTRACK LABEL_TABS+65

#define LABEL_PARAMS 160
#define LABEL_CAM2PROJ_MIN_CONFIDENCE LABEL_PARAMS+0
#define LABEL_CAM2PROJ_MIN_RANGE LABEL_PARAMS+1
#define LABEL_CAM2PROJ_CONFIDENCE_THRESHOLD LABEL_PARAMS+2
#define LABEL_CAM2PROJ_NOISE LABEL_PARAMS+3
#define LABEL_CAM2PROJ_CROP LABEL_PARAMS+4
#define LABEL_COLOR_CONFIDENCE LABEL_PARAMS+5
#define LABEL_UVMAP_VMIDDLE LABEL_PARAMS+6
#define LABEL_UVMAP_INNER_SCALE LABEL_PARAMS+7
#define LABEL_UVMAP_OUTER_SCALE LABEL_PARAMS+8
#define LABEL_CAPTURE_MODE LABEL_PARAMS+9
#define LABEL_CAPTURE_STL_ONLY LABEL_PARAMS+10
#define LABEL_CAPTURE_CAMERA LABEL_PARAMS+11
#define LABEL_CAPTURE_DISTO LABEL_PARAMS+12
#define LABEL_CAPTURE_DISTO_K1 LABEL_PARAMS+13
#define LABEL_CAPTURE_DISTO_K2 LABEL_PARAMS+14
#define LABEL_CAPTURE_CAMID LABEL_PARAMS+15
#define LABEL_CAPTURE_INTERVAL LABEL_PARAMS+16
#define LABEL_CAPTURE_TRANSFER LABEL_PARAMS+17
#define LABEL_CAPTURE_TEST LABEL_PARAMS+18
#define LABEL_PRECROP_HEADER LABEL_PARAMS+19
#define LABEL_PRECROP_WIDTH LABEL_PARAMS+20
#define LABEL_PRECROP_HEIGHT LABEL_PARAMS+21
#define LABEL_SMOOTH_NB_PATCHES_X LABEL_PARAMS+22
#define LABEL_SMOOTH_NB_PATCHES_Y LABEL_PARAMS+23
#define LABEL_GAMMA_MANUAL LABEL_PARAMS+24
#define LABEL_GAMMA_CAMERA_R LABEL_PARAMS+25
#define LABEL_GAMMA_CAMERA_G LABEL_PARAMS+26
#define LABEL_GAMMA_CAMERA_B LABEL_PARAMS+27
#define LABEL_GAMMA_PROJECTOR_R LABEL_PARAMS+28
#define LABEL_GAMMA_PROJECTOR_G LABEL_PARAMS+29
#define LABEL_GAMMA_PROJECTOR_B LABEL_PARAMS+30
#define LABEL_UV2PROJ_ANGLE_PROJ_MAX LABEL_PARAMS+31
#define LABEL_PATTERN_FREQUENCY LABEL_PARAMS+32
#define LABEL_PATTERN_NB LABEL_PARAMS+33

#define LABEL_MESSAGES 200
#define LABEL_SAVE_PROJECT LABEL_MESSAGES+0
#define LABEL_PROJECT_CHOOSE_FILE LABEL_MESSAGES+1
#define LABEL_PLAYLIST_CHOOSE_FILENAME LABEL_MESSAGES+2
#define LABEL_PLAYLIST_ENTER_FILENAME LABEL_MESSAGES+3
#define LABEL_NEW_PLAYLIST_SAVE_PREVIOUS LABEL_MESSAGES+4
#define LABEL_PLAYLIST_FILES LABEL_MESSAGES+5
#define LABEL_DELETE_MEDIA LABEL_MESSAGES+6
#define LABEL_DELETE_CAMERA_FILES LABEL_MESSAGES+7
#define LABEL_CHOOSE_DIRECTORY LABEL_MESSAGES+8
#define LABEL_CAMERA_FILE_LOCATION LABEL_MESSAGES+9

#define LABEL_CHOICES 210
#define LABEL_CHOICE_LEFT LABEL_CHOICES+0
#define LABEL_CHOICE_RIGHT LABEL_CHOICES+1
#define LABEL_CHOICE_ALL LABEL_CHOICES+2
#define LABEL_CHOICE_PATTERNS LABEL_CHOICES+3
#define LABEL_CHOICE_GAMMA LABEL_CHOICES+4
#define LABEL_CHOICE_COLOR LABEL_CHOICES+5
#define LABEL_CHOICE_NOISE LABEL_CHOICES+6
#define LABEL_CHOICE_AUTOMATIC LABEL_CHOICES+7
#define LABEL_CHOICE_MANUAL LABEL_CHOICES+8

#define LABEL_SOUND_SUBWOOFER 220

#define NB_LANG_LABELS 221

#ifdef __cplusplus
extern "C" {
#endif

unsigned char langGet();
int langSet(unsigned char l);
char *langGetLabel(unsigned char label);
void langInit();

int setFloatSpinner(Fl_Spinner *spin,double vmin,double vmax,int *lineposy);
int setIntegerSpinner(Fl_Spinner *spin,int vmin,int vmax,int *lineposy);
int setInput(Fl_Input *input,int *lineposy);
int setButton(Fl_Button *but,int *lineposy);
int setChoice(Fl_Choice *choice,int *lineposy);
int setCheckButton(Fl_Check_Button *check,int *lineposy);
int setSlider(Fl_Slider *slider,int *lineposy);
int setBox(Fl_Box *box,int *lineposy);

Fl_Color getGrayLevel(double i);
void box_user_draw(int x, int y, int w, int h, Fl_Color c);

#ifdef __cplusplus
}
#endif

#endif

